[package]
name = "artyminal"
version = "0.1.0"
authors = ["papadoc"]

[lib]
name = "artyminal"
path = "src/lib.rs"

[[bin]]
name = "artyshell"
path = "src/main.rs"

[dependencies]
dirs = "*"

[target.'cfg(unix)'.dependencies]
termion = "*"
